### ISSUE TITLE
npm run lint:format

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/markdown-it-plugin-template#6]
Add prettier to our lint test in the ci.

I have done this as `npm run lint:format` in the past (as well as a `npm run lint:format:fix`)

See [example](https://github.com/curvenote/editor/blob/main/package.json#L39).

Happy to make the various PRs for this and #5.

**Comment by chrisjsewell** [comment]
prettier is already set up as a plugin to eslint, you don't need a separate script, e.g.

```
(base) markdown-it-plugin-template/$ npm run lint    

> markdown-it-plugin-template@0.2.1 lint
> eslint -c .eslintrc.yml --max-warnings 1 src/**/*.ts tests/**/*.ts


/Users/chrisjsewell/Documents/GitHub/markdown-it-plugin-template/src/index.ts
  14:44  error  Delete `·`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

and run `npm run lint:fix` to fix it.

or am I missing something?

**Comment by rowanc1** [comment]
Oh boy, yep - all good. I am too used to introducing this incrementally to existing repos and monorepos where I am a bit more selective on when to apply. It is working as expected.

**Comment by chrisjsewell** [comment]
>  I am too used to introducing this incrementally to existing repos and monorepos where I am a bit more selective on when to apply.

yep; you either do it properly from the start or not at all 😆
